apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: integration-frontend-toolkit
  annotations:
    github.com/project-slug: contentful/integration-frontend-toolkit

spec:
  type: library
  lifecycle: production
  owner: group:team-developer-experience
